language: node_js
node_js:
  - "iojs"
  - "11"
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  target-branch: gh-pages
  verbose: true
  on:
    branch: master