language: node_js
node_js:
  - "iojs"
  - "7"
deploy:
  provider: npm
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: src
  target-branch: gh-pages
  verbose: true
  on:
    branch: master